version: '3.1'
services:
    mysql:
        image: mariadb:10.2
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=airflow
            - MYSQL_DATABASE=airflow
            - MYSQL_USER=airflow
            - MYSQL_PASSWORD=airflow

    redis:
        image: 'redis:3.2.7'
        # command: redis-server --requirepass redispass

    webserver:
        image: diraol/airflow:1.9.0
        restart: always
        depends_on:
            - redis
            - mysql
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - PYTHONPATH=/env_packages
            # - REDIS_PASSWORD=redispass
        volumes:
            - ./BI:/usr/local/airflow/BI
            - ./dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins 
            # - ./plugins:/usr/local/airflow/plugins
            - ./requirements.txt:/requirements.txt
            - ./env_packages:/env_packages
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

    flower:
        image: diraol/airflow:1.9.0
        restart: always
        depends_on:
            - redis
        environment:
            - EXECUTOR=Celery
            # - REDIS_PASSWORD=redispass
        ports:
            - "5555:5555"
        command: flower
        volumes:
            - ./requirements.txt:/requirements.txt

    scheduler:
        image: diraol/airflow:1.9.0
        restart: always
        depends_on:
            - webserver
        volumes:
            - ./BI:/usr/local/airflow/BI
            - ./dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins 
            # - ./plugins:/usr/local/airflow/plugins
            - ./requirements.txt:/requirements.txt
            - ./env_packages:/env_packages
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - PYTHONPATH=/env_packages
            # - REDIS_PASSWORD=redispass
        command: scheduler

    worker:
        image: diraol/airflow:1.9.0
        restart: always
        depends_on:
            - scheduler
        volumes:
            - ./BI:/usr/local/airflow/BI
            - ./dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins 
            # - ./plugins:/usr/local/airflow/plugins
            - ./requirements.txt:/requirements.txt
            - ./env_packages:/env_packages
        environment:
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
            - PYTHONPATH=/env_packages
            # - REDIS_PASSWORD=redispass
        command: worker
